/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectbai3sw;

import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;  


/**
 *
 * @author theunforgiven
 */
public class bai3 extends javax.swing.JFrame {

    /**
     * Creates new form bai3
     */
    public bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DS = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        YT = new javax.swing.JList<>();
        Right = new javax.swing.JButton();
        AllRight = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        AllLeft = new javax.swing.JButton();
        BtnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(DS);

        jScrollPane2.setViewportView(YT);

        Right.setText(">");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });

        AllRight.setText(">>");
        AllRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRightActionPerformed(evt);
            }
        });

        Left.setText("<");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });

        AllLeft.setText("<<");
        AllLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllLeftActionPerformed(evt);
            }
        });

        BtnThem.setText("+");
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("DS Môn thể thao");

        jLabel2.setText("Môn yêu thích");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllRight, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AllRight)
                                .addGap(18, 18, 18)
                                .addComponent(Left)
                                .addGap(18, 18, 18)
                                .addComponent(AllLeft))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRightActionPerformed
        // TODO add your handling code here:
        ListModel dsTen = DS.getModel();
        ListModel dsMon = YT.getModel();
        ArrayList<String> arr = new ArrayList<>();
        for(int i = 0; i < dsMon.getSize();i++)
        {
            String ten = dsMon.getElementAt(i).toString();
            arr.add(ten);
        }
        
        for(int i = 0; i<dsTen.getSize();i++)
        {
            String ten = dsTen.getElementAt(i).toString();
            arr.add(ten);
        }
        
        String[] data = arr.toArray(new String[0]);
        YT.setListData(data);
        arr.removeAll(arr);
        data =  arr.toArray(new String[0]);
        DS.setListData(data);
    }//GEN-LAST:event_AllRightActionPerformed

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
    //Them
    JFrame f;   
    f=new JFrame();   
    String name=JOptionPane.showInputDialog(f,"Nhập môn thể thao");
    //Them
    ListModel dsTen= DS.getModel();
    ArrayList<String> arrTen = new ArrayList<>();
        int i=0;
        for (i=0; i<dsTen.getSize(); i++)
        {   
            String ten =dsTen.getElementAt(i).toString();
            arrTen.add(ten);
        }
        arrTen.add(name);
        // chuyển sang kiểu mảng để đưa vào JList
        
        String[] mTen = arrTen.toArray(new String[arrTen.size()]);
        DS.setListData((String[]) mTen);
    }//GEN-LAST:event_BtnThemActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
        
        
        //XOa
        ListModel dsTen=DS.getModel();
        ArrayList<String> arrTen = new ArrayList<>();
        int i=0;
        for (i=0; i<dsTen.getSize(); i++)
        {   
            String ten =dsTen.getElementAt(i).toString();
            arrTen.add(ten);
        }
        int a = DS.getSelectedIndex();
        
        arrTen.remove(dsTen.getElementAt(a));
        String[] mTen = arrTen.toArray(new String[0]);
        DS.setListData(mTen);
        //Them
        
        ListModel dsMon= YT.getModel();
        ArrayList<String> arrMon = new ArrayList<>();
      
        for (int j=0; j<dsMon.getSize(); j++)
        {   
            String ten =dsMon.getElementAt(j).toString();
            arrMon.add(ten);
        }
        
        arrMon.add((String) dsTen.getElementAt(a));
        String[] mMon = arrMon.toArray(new String[arrMon.size()]);
        YT.setListData(mMon);
        //ArrayList<String> arrTen = new ArrayList<>();
        //for(i)
    }//GEN-LAST:event_RightActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        // TODO add your handling code here:
        ListModel dsMon=YT.getModel();
        ArrayList<String> arrMon = new ArrayList<>();
        int i=0;
        for (i=0; i<dsMon.getSize(); i++)
        {   
            String ten =dsMon.getElementAt(i).toString();
            arrMon.add(ten);
        }
        int a = YT.getSelectedIndex();
        
        arrMon.remove(dsMon.getElementAt(a));
        String[] mMon = arrMon.toArray(new String[0]);
        YT.setListData(mMon);
        //Them
        
        ListModel dsTen= DS.getModel();
        ArrayList<String> arrTen = new ArrayList<>();
      
        for (int j=0; j<dsTen.getSize(); j++)
        {   
            String ten =dsTen.getElementAt(j).toString();
            arrTen.add(ten);
        }
        
        arrTen.add((String) dsMon.getElementAt(a));
        String[] mTen = arrTen.toArray(new String[arrTen.size()]);
        DS.setListData(mTen);
    }//GEN-LAST:event_LeftActionPerformed

    private void AllLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllLeftActionPerformed
        // TODO add your handling code here:
        ListModel dsTen = DS.getModel();
        ListModel dsMon = YT.getModel();
        ArrayList<String> arr = new ArrayList<>();
        for(int i = 0; i < dsTen.getSize();i++)
        {
            String ten = dsTen.getElementAt(i).toString();
            arr.add(ten);
        }
        
        for(int i = 0; i<dsMon.getSize();i++)
        {
            String ten = dsMon.getElementAt(i).toString();
            arr.add(ten);
        }
        
        String[] data = arr.toArray(new String[0]);
        DS.setListData(data);
        arr.removeAll(arr);
        data =  arr.toArray(new String[0]);
        YT.setListData(data);
    }//GEN-LAST:event_AllLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllLeft;
    private javax.swing.JButton AllRight;
    private javax.swing.JButton BtnThem;
    private javax.swing.JList<String> DS;
    private javax.swing.JButton Left;
    private javax.swing.JButton Right;
    private javax.swing.JList<String> YT;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
